### ISSUE TITLE
make on OSX is broken: `emacs: Invalid function cdr`

### ISSUE THREAD

**Issue by philippkeller** [Wilfred/remacs#91] opened 2017-01-19 15:02 UTC
Steps before the error:

```
./autogen.sh
/configure --without-makeinfo
brew install gnutls
make
```

## Error produced

```
mv -f remacs bootstrap-emacs
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../lisp compile-first EMACS="../src/bootstrap-emacs"
  GEN      calendar/cal-loaddefs.el
emacs: Invalid function: cdr
make[2]: *** [calendar/cal-loaddefs.el] Error 1
make[1]: *** [bootstrap-emacs] Error 2
make: *** [src] Error 2
```

## Environment

- OSX Sierra 10.12.2 (16C67)
- GNU Make 3.81
- Darwin 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
- xcode-select version 2347

**Comment by Wilfred** [comment] 2017-01-19 23:39
Duplicate of #38.

**Closed by Wilfred** 2017-01-19 23:39 UTC
