### ISSUE TITLE
Fail to compile remacs on i686 Linux

### ISSUE THREAD

**Issue by thierryvolpiatto** [Wilfred/remacs#294] opened 2017-08-20 15:20 UTC
Hi, I am already using remacs on another laptop (more recent, 64b) and remacs compile fine and works great on it, thanks for your work.
However I wanted to compile it on my old laptop:
uname -a
Linux MM061 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:57:50 UTC 2017 i686 i686 i686 GNU/Linux

and it fails at:

Loading /home/thierry/tmp/remacs/lisp/emacs-lisp/cl-generic.el (source)...
Makefile:761 : la recette pour la cible « bootstrap-emacs » a échouée
make[1]: *** [bootstrap-emacs] Erreur de segmentation
make[1] : on quitte le répertoire « /home/thierry/tmp/remacs/src »
Makefile:426 : la recette pour la cible « src » a échouée
make: *** [src] Erreur 2

With make LC_ALL=C

Loading /home/thierry/tmp/remacs/lisp/emacs-lisp/cl-generic.el (source)...
Makefile:761: recipe for target 'bootstrap-emacs' failed
make[1]: *** [bootstrap-emacs] Segmentation fault
make[1]: Leaving directory '/home/thierry/tmp/remacs/src'
Makefile:426 : la recette pour la cible « src » a échouée
make: *** [src] Erreur 2

Any idea ?

Thanks.

**Comment by Wilfred** [comment] 2017-08-31 21:02
Argh. We've had compilation fail in the past for 32-bit, but it was fixed. It's clearly broken again. We only build 64-bits on Travis, so it's easy to accidentally break. We should add this to the build, somehow.

**Comment by birkenfeld** [comment] 2017-09-19 06:41
There seems to be no easy option to build on a 32-bit machine (https://github.com/travis-ci/travis-ci/issues/986). Other projects use the multilib support on Ubuntu and `gcc -m32` but I'm not clear how that would work for our Rust parts.

**Comment by shaleh** [comment] 2017-10-26 16:14
A quick solution would be to use something like https://github.com/docker-32bit/ubuntu

**Comment by shaleh** [comment] 2017-10-26 16:38
I just tried this and hit a failure. Likely a Rust nightly issue....

    Finished release [optimized] target(s) in 5.46 secs
  CCLD     etags
../rust_src/remacs-lib/target/release/libremacs_lib.a(remacs_lib-ad29e16b26dfc90d.remacs_lib0.rust-cgu.o): In function `_$LT$core..str..pattern..StrSearcher$LT$$u27$a$C$$u20$$u27$b$GT$$u20$as$u20$core..str..pattern..Searcher$LT$$u27$a$GT$$GT$::next::hca114ed2c9ea9984':
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN122_$LT$core..str..pattern..StrSearcher$LT$$u27$a$C$$u20$$u27$b$GT$$u20$as$u20$core..str..pattern..Searcher$LT$$u27$a$GT$$GT$4next17hca114ed2c9ea9984E+0x6d5): undefined reference to `core::panicking::panic_bounds_check::h24459df8c622844c'
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN122_$LT$core..str..pattern..StrSearcher$LT$$u27$a$C$$u20$$u27$b$GT$$u20$as$u20$core..str..pattern..Searcher$LT$$u27$a$GT$$GT$4next17hca114ed2c9ea9984E+0x6ed): undefined reference to `core::panicking::panic_bounds_check::h24459df8c622844c'
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN122_$LT$core..str..pattern..StrSearcher$LT$$u27$a$C$$u20$$u27$b$GT$$u20$as$u20$core..str..pattern..Searcher$LT$$u27$a$GT$$GT$4next17hca114ed2c9ea9984E+0x705): undefined reference to `core::panicking::panic_bounds_check::h24459df8c622844c'
../rust_src/remacs-lib/target/release/libremacs_lib.a(remacs_lib-ad29e16b26dfc90d.remacs_lib0.rust-cgu.o): In function `_$LT$alloc..arc..Arc$LT$T$GT$$GT$::drop_slow::h7bc55406bd95f616':
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN33_$LT$alloc..arc..Arc$LT$T$GT$$GT$9drop_slow17h7bc55406bd95f616E+0x1c): undefined reference to `std::sys::imp::mutex::ReentrantMutex::destroy::hc9f05901dff85515'
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN33_$LT$alloc..arc..Arc$LT$T$GT$$GT$9drop_slow17h7bc55406bd95f616E+0x3c0): undefined reference to `core::panicking::panic::hbf9391b2a1f00acc'
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN33_$LT$alloc..arc..Arc$LT$T$GT$$GT$9drop_slow17h7bc55406bd95f616E+0x3df): undefined reference to `core::panicking::panic::hbf9391b2a1f00acc'
../rust_src/remacs-lib/target/release/libremacs_lib.a(remacs_lib-ad29e16b26dfc90d.remacs_lib0.rust-cgu.o): In function `_$LT$alloc..vec..Vec$LT$T$GT$$GT$::extend_from_slice::ha53f77bbcc352848':
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text._ZN33_$LT$alloc..vec..Vec$LT$T$GT$$GT$17extend_from_slice17ha53f77bbcc352848E+0xf3): undefined reference to `core::panicking::panic::hbf9391b2a1f00acc'
../rust_src/remacs-lib/target/release/libremacs_lib.a(remacs_lib-ad29e16b26dfc90d.remacs_lib0.rust-cgu.o): In function `std::panicking::begin_panic::hcc2c1d9605ceffc7':
remacs_lib0-6b04de8b5081fa8c3d76fb5099ac5cb2.rs:(.text.cold._ZN3std9panicking11begin_panic17hcc2c1d9605ceffc7E+0x4b): undefined reference to `std::panicking::rust_panic_with_hook::h7a8fa3053f49f20c'

**Comment by shaleh** [comment] 2017-10-26 16:38
I will post a Dockerfile32bit PR in a few hours.

**Comment by shaleh** [comment] 2017-10-26 22:05
Looks like nightly just does not like i686....

 = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit0.rust-cgu.o" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit1.rust-cgu.o" "-o" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f" "/root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/root/test32bit/target/debug/deps" "-L" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-f64e65221ded4189.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_jemalloc-15603b85f9b07db5.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_system-7f202905b2f90235.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-fd7102ed26e1ee75.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librand-b2608977e05bf703.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-3d18fc673b5da13d.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-390d7866de44001e.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-28619888b40bbbe2.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_unicode-6e3e1588214a0702.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-a30e14812908fc60.rlib" "/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-20161fbf48c6c15f.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit0.rust-cgu.o: In function `test32bit::main':
          /root/test32bit/src/main.rs:2: undefined reference to `std::io::stdio::_print::h6c953456faaea52a'
          /root/test32bit/target/debug/deps/test32bit-4197078e3788cd4f.test32bit0.rust-cgu.o: In function `main':
          /root/test32bit/src/main.rs:(.text.main+0x37): undefined reference to `std::rt::lang_start::hb4e4c925bf3928b1'
          collect2: error: ld returned 1 exit status

That is a simple 'cargo init test32bit --bin && cd test32bit && cargo build`. It works for stable and fails for nightly.

**Comment by shaleh** [comment] 2017-10-26 22:07
https://github.com/rust-lang/rust/issues/45500

**Comment by shaleh** [comment] 2017-11-02 23:55
Ok, the Rust issue building 32bit is fixed. I can now reproduce the segfault in temacs.

gdb was unable to catch the backtrace, it happened to early in the program startup.

**Comment by shaleh** [comment] 2017-11-02 23:57
I checked in a 32bit dockerfile a little bit ago. You can now use it to build 32 bit docker images easily.

`docker build -f Dockerfile32bit -t remacs32bit .`

**Comment by jamcha-aa** [comment] 2017-12-10 11:04
Thanks. I have successfully built on my 32bit Linux laptop.

System:
uname -a
Linux user-1000H 4.10.0-42-generic \# 46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 i686 i686 i686 GNU/Linux

Compiler:
rustc --version
rustc 1.24.0-nightly (ad3543db3 2017-12-08)

rustup show
Default host: i686-unknown-linux-gnu

**installed toolchains**
stable-i686-unknown-linux-gnu
nightly-2017-11-12-i686-unknown-linux-gnu
nightly-i686-unknown-linux-gnu

**active toolchain**
nightly-i686-unknown-linux-gnu (directory override for '/home/user/Documents/Git/remacs')
rustc 1.24.0-nightly (ad3543db3 2017-12-08)

Procedure:
```
$ sed -i -e "s/i64/i32/g" rust_src/src/lisp.rs
$ ./autogen.sh
$ ./configure --build=i686-pc-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32" --enable-rust-debug
$ RUST_BACKTRACE=0 make
```

**Comment by shaleh** [comment] 2017-12-10 16:39
That is helpful @jamcha-aa thank you.

**Comment by shaleh** [comment] 2017-12-14 07:14
This ticket can be closed. Rust toolchain works and our 32 bit mistakes have been handled.

**Closed by shaleh** 2017-12-14 07:14 UTC
Labels: bug
