### ISSUE TITLE
buffers shown twice in helm buffer

### ISSUE THREAD

**Issue by manfredlotz** [Wilfred/remacs#994] opened 2018-11-01 19:06 UTC
I just cloned remacs and build the binary. 

I'm using Spacemacs, and found that in Helm buffer all buffers (except Messages) are shown twice.

**Comment by brotzeit** [comment] 2018-11-01 19:22
I can confirm that.

**Comment by manfredlotz** [comment] 2018-11-09 14:46
Does it mean you fixed it? I pulled 35bf05606622804ad2728600dc46c12dd854cecb and rebuilt

`make clean && ./autogen.sh && ./configure && make`

but the buffers are still shown twice as before. Additionally, the keyboard cursor has disppeared.

Means it is unusable right now.

**Comment by brotzeit** [comment] 2018-11-09 14:53
I meant it was tricky to find it, since regular `buffer-list` behaves differently than `helm-mini` and you have to execute helm-mini more than once to see the duplicates. I'm waiting for @shaleh since he ported the function and knows better than me what to do. But I'm sure it's fixed soon.

**Comment by brotzeit** [comment] 2018-11-09 14:54
And keyboard cursor is fixed by #1030

**Comment by manfredlotz** [comment] 2018-11-09 14:55
Actually, I'll be away for vacation in an hour or two. So from my perspective, no hurry. :-)

Nevertheless, thanks a lot for your (you and all others working on it) great work.

**Comment by manfredlotz** [comment] 2018-11-09 14:56
> And keyboard cursor is fixed by #1030

Aah, good

**Comment by brotzeit** [comment] 2018-11-09 15:39
Thanks for using remacs and reporting bugs. This bug was almost a year old. I have to admit I don't use remacs(I would have encountered this bug myself if I would). I have used it when I started contributing to this project but something didn't work these days in remacs, but I can't even remember what it was =)
I guess it's time to change this.

**Comment by shaleh** [comment] 2018-11-09 17:10
Thanks for the PR identifying the issue @brotzeit. I made an updated PR to put the bool back but check it properly.

**Comment by shaleh** [comment] 2018-11-09 17:31
Will do. But it will be tonight at the earliest, maybe tomorrow night.

**Comment by brotzeit** [comment] 2018-11-09 17:52
There's no hurry. I'm still waiting for a regression where I'm able to use git bisect =)

**Comment by shaleh** [comment] 2018-11-09 18:34
Yeah, if someone can identify where we broke it that would be super helpful.

**Comment by shaleh** [comment] 2018-11-10 00:03
Ok, in top of tree remacs if I run `(buffer-list)` i get this:

```
(#<buffer *scratch*> #<buffer *eshell*> #<buffer  *Minibuf-1*> #<buffer  *Minibuf-0*> #<buffer *Messages*> #<buffer  *code-conversion-work*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *autoload*> #<buffer *Compile-Log*>)
```

No duplicates. Looks sane.

Can someone post an example of when it is not correct?

**Comment by shaleh** [comment] 2018-11-10 00:04
i just opened two files. Still looks accurate:

```
(#<buffer *scratch*> #<buffer CONTRIBUTORS> #<buffer  *Minibuf-1*> #<buffer CONTRIBUTING.md> #<buffer *eshell*> #<buffer  *Minibuf-0*> #<buffer *Messages*> #<buffer  *code-conversion-work*> #<buffer  *Echo Area 0*> #<buffer  *Echo Area 1*> #<buffer  *autoload*> #<buffer *Compile-Log*>)
```

**Comment by brotzeit** [comment] 2018-11-10 09:54
I'm also still confused by this bug. I'm not sure what helm is doing here.

**Comment by shaleh** [comment] 2018-11-10 10:08
I have never used helm. How do I reproduce the bug?

**Comment by shaleh** [comment] 2018-11-10 11:03
`helm-mini` calls `ido`. `ido` calls `(buffer-list frame)` and finally, we have a reproducible bug!

Fire up `ielm` and type `(buffer-list)`. All looks normal. Now try `(buffer-list (selected-frame))`. Notice the repeats.

That should get you pointed in the right direction.

**Closed** 2018-11-11 17:13 UTC
Labels: bug

**Comment by manfredlotz** [comment] 2018-11-29 13:53
(Now being back from vacation) Just to confirm that the helm buffer looks good now. Thanks a lot for your help.
