### ISSUE TITLE
remacs build fails on macOS with 'libjpeg not loaded'

### ISSUE THREAD

**Issue by raxod502** [Wilfred/remacs#295] opened 2017-08-26 02:34 UTC
Building from a fresh checkout of revision 5c4747a0149cab7d16aa5cc8ba9a61540a730a14
 gives the following error:

```
  CC       kqueue.o
  CC       profiler.o
  CC       decompress.o
  CC       thread.o
  CC       systhread.o
  CC       fontset.o
  CC       fringe.o
  CC       image.o
  CC       nsterm.o
  CC       nsfns.o
  CC       nsmenu.o
  CC       nsselect.o
  CC       nsimage.o
gmake[1]: Circular bootstrap-emacs <- temacs dependency dropped.
gmake -C ../admin/unidata all EMACS="../../src/bootstrap-emacs"
gmake[2]: Entering directory '/Users/raxod502/files/code/emacs/remacs/admin/unidata'
  GEN      ../../src/macuvs.h
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /Users/raxod502/files/code/emacs/remacs/admin/unidata/../../src/bootstrap-emacs
  Reason: image not found
/bin/sh: line 2:  4474 Trace/BPT trap: 5       "../../src/bootstrap-emacs" -batch --no-site-file --no-site-lisp -L . -l uvs --eval '(uvs-print-table-ivd (unmsys--file-name "./IVD_Sequences.txt") "Adobe-Japan1")' > ../../src/macuvs.h
gmake[2]: *** [Makefile:67: ../../src/macuvs.h] Error 133
gmake[2]: Leaving directory '/Users/raxod502/files/code/emacs/remacs/admin/unidata'
gmake[1]: *** [Makefile:511: macuvs.h] Error 2
gmake[1]: Leaving directory '/Users/raxod502/files/code/emacs/remacs/src'
gmake: *** [Makefile:426: src] Error 2
```

The exact sequence of commands was:

```
$ git pull
$ git checkout .
$ git clean -fd
$ ./autogen.sh
$ ./configure
$ make
```

I already have `libjpeg` installed via Homebrew:

```
$ brew install libjpeg
Warning: jpeg 9b is already installed
```

Configuring with `./configure --without-jpeg` produces a similar error:

```
  CC       kqueue.o
  CC       profiler.o
  CC       decompress.o
  CC       thread.o
  CC       systhread.o
  CC       fontset.o
  CC       fringe.o
  CC       image.o
  CC       nsterm.o
  CC       nsfns.o
  CC       nsmenu.o
  CC       nsselect.o
  CC       nsimage.o
gmake[1]: Circular bootstrap-emacs <- temacs dependency dropped.
gmake -C ../admin/unidata all EMACS="../../src/bootstrap-emacs"
gmake[2]: Entering directory '/Users/raxod502/files/code/emacs/remacs/admin/unidata'
  ELC      unidata-gen.elc
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /Users/raxod502/files/code/emacs/remacs/admin/unidata/../../src/bootstrap-emacs
  Reason: image not found
/bin/sh: line 1: 16025 Trace/BPT trap: 5       "../../src/bootstrap-emacs" -batch --no-site-file --no-site-lisp -f batch-byte-compile unidata-gen.el
gmake[2]: *** [Makefile:72: unidata-gen.elc] Error 133
gmake[2]: Leaving directory '/Users/raxod502/files/code/emacs/remacs/admin/unidata'
gmake[1]: *** [Makefile:511: macuvs.h] Error 2
gmake[1]: Leaving directory '/Users/raxod502/files/code/emacs/remacs/src'
gmake: *** [Makefile:426: src] Error 2
```

System information:

```
                -/+:.           raxod502@Radon-MBP-New.local
               :++++.           ----------------------------
              /+++/.            OS: OS X El Capitan 10.11.6 15G1611 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro11,3
   .:/++++++/::::/++++++/:`     Kernel: 15.6.0
 .:///////////////////////:`    Uptime: 4 days, 8 hours, 38 minutes
 ////////////////////////`      Packages: 406
-+++++++++++++++++++++++`       Shell: zsh 5.4.1
/++++++++++++++++++++++/        Resolution: 3008x1692@2x, 1440x900@2x
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal: iTerm2
  `ossssssssssssssssssssss/     Terminal Font: InputMono-Medium 14
    :ooooooooooooooooooo+.      CPU: Intel i7-4980HQ (8) @ 2.80GHz
     `:+oo+/:-..-:/+o+/-        GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
                                Memory: 3927MiB / 16384MiB
```

**Comment by shaleh** [comment] 2017-12-29 11:03
We are not seeing this in the automated Travis builds. Should we close it?

**Comment by Wilfred** [comment] 2017-12-30 13:44
I think so. The code has changed substantially since August.

Feel free to reopen if the issue is still occurring.

**Closed by Wilfred** 2017-12-30 13:44 UTC

**Comment by raxod502** [comment] 2017-12-31 06:44
I can confirm that building from revision f39bebae4083a93b263603cdb92ee228b4d697d9 is successful; thanks!

**Comment by shaleh** [comment] 2017-12-31 06:45
@raxod502 we appreciate the confirmation
